---

dependencies:

  - role: logstash/baremetal
    when: logstash_install_type == "baremetal"

  - role: logstash/docker
    when: logstash_install_type == "docker"

  - role: logstash/kubernetes
    when: logstash_install_type == "kubernetes"
